// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm8oT5VT_yGGzpfL3Kf0TFz2KJ1vR1W0Q', // Will be generated later
    appId: '1:427229818801:web:seedfyapp',
    messagingSenderId: '427229818801',
    projectId: 'seedfyapp',
    authDomain: 'seedfyapp.firebaseapp.com',
    storageBucket: 'seedfyapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm8oT5VT_yGGzpfL3Kf0TFz2KJ1vR1W0Q',
    appId: '1:427229818801:android:seedfyapp',
    messagingSenderId: '427229818801',
    projectId: 'seedfyapp',
    storageBucket: 'seedfyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm8oT5VT_yGGzpfL3Kf0TFz2KJ1vR1W0Q',
    appId: '1:427229818801:ios:seedfyapp',
    messagingSenderId: '427229818801',
    projectId: 'seedfyapp',
    storageBucket: 'seedfyapp.appspot.com',
    iosBundleId: 'com.example.seedfyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm8oT5VT_yGGzpfL3Kf0TFz2KJ1vR1W0Q',
    appId: '1:427229818801:macos:seedfyapp',
    messagingSenderId: '427229818801',
    projectId: 'seedfyapp',
    storageBucket: 'seedfyapp.appspot.com',
    iosBundleId: 'com.example.seedfyApp',
  );
}