name: Build APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        cache: true

    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze --fatal-infos

    - name: Run tests
      run: flutter test --coverage

    - name: Setup Firebase config
      env:
        GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
      run: |
        if [ ! -z "$GOOGLE_SERVICES_JSON_BASE64" ]; then
          echo $GOOGLE_SERVICES_JSON_BASE64 | base64 -d > android/app/google-services.json
        else
          echo "Warning: GOOGLE_SERVICES_JSON_BASE64 secret not found, using existing file"
        fi

    - name: Build Debug APK
      run: flutter build apk --debug --target-platform android-arm64,android-arm,android-x64

    - name: Build Release APK
      run: flutter build apk --release --target-platform android-arm64,android-arm,android-x64

    - name: Build App Bundle (AAB)
      run: flutter build appbundle --release --target-platform android-arm64,android-arm,android-x64

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: seedfy-debug-apk-${{ github.run_number }}
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 30

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: seedfy-release-apk-${{ github.run_number }}
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 90

    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: seedfy-app-bundle-${{ github.run_number }}
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 90

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0-${{ steps.date.outputs.date }}-${{ github.run_number }}
        name: Seedfy Release v1.0.0-${{ steps.date.outputs.date }}-${{ github.run_number }}
        body: |
          🌱 **Seedfy App Release**
          
          **Build Information:**
          - Commit: ${{ github.sha }}
          - Build date: ${{ steps.date.outputs.date }}
          - Build number: ${{ github.run_number }}
          - Branch: ${{ github.ref_name }}
          
          **Downloads:**
          - **app-debug.apk**: Para testes e desenvolvimento
          - **app-release.apk**: Para instalação em produção
          - **app-release.aab**: Para distribuição na Google Play Store (recomendado)
          
          **Supported Architectures:**
          - ARM64 (arm64-v8a)
          - ARM32 (armeabi-v7a)
          - x86_64
        files: |
          build/app/outputs/flutter-apk/app-debug.apk
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
